import type { Builder, RewardProgram } from "@/types";

export const MOCK_BUILDERS: Builder[] = [
  {
    id: "1",
    rank: 1,
    name: "xqc",
    handle: "xqcxx",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=xqcxx",
    monthlyReward: 750,
    allTimeReward: 4200,
    contractsDeployed: 18,
    githubContributions: 94,
    walletAddress: "SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ",
    githubProfile: "https://github.com/xqcxx",
    ecosystem: ["DeFi", "NFT"],
    joinedDate: "2023-01-15",
    bio: "Core contributor to the Stacks ecosystem. Building DeFi primitives on Bitcoin.",
    isVerified: true,
  },
  {
    id: "2",
    rank: 2,
    name: "agedevs",
    handle: "agedevs",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=agedevs",
    monthlyReward: 750,
    allTimeReward: 3800,
    contractsDeployed: 12,
    githubContributions: 78,
    walletAddress: "SP1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE",
    githubProfile: "https://github.com/agedevs",
    ecosystem: ["Infrastructure", "DeFi"],
    joinedDate: "2023-03-22",
    bio: "Smart contract developer focused on secure financial primitives.",
    isVerified: true,
  },
  {
    id: "3",
    rank: 3,
    name: "floxy",
    handle: "floxxih",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=floxxih",
    monthlyReward: 750,
    allTimeReward: 3500,
    contractsDeployed: 9,
    githubContributions: 65,
    walletAddress: "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE",
    githubProfile: "https://github.com/floxxih",
    ecosystem: ["NFT", "Gaming"],
    joinedDate: "2023-05-10",
    bio: "NFT tooling and gaming infrastructure on Stacks.",
    isVerified: true,
  },
  {
    id: "4",
    rank: 4,
    name: "diabblo",
    handle: "diiabblo",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=diiabblo",
    monthlyReward: 750,
    allTimeReward: 3100,
    contractsDeployed: 7,
    githubContributions: 55,
    walletAddress: "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR",
    githubProfile: "https://github.com/diiabblo",
    ecosystem: ["DeFi"],
    joinedDate: "2023-07-08",
    bio: "Liquidity protocol builder on Bitcoin Layer 2.",
    isVerified: false,
  },
  {
    id: "5",
    rank: 5,
    name: "Investorphem",
    handle: "investorphem",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=investorphem",
    monthlyReward: 750,
    allTimeReward: 2900,
    contractsDeployed: 5,
    githubContributions: 48,
    walletAddress: "SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0",
    githubProfile: "https://github.com/investorphem",
    ecosystem: ["DAO", "Social"],
    joinedDate: "2023-08-14",
    bio: "DAO tooling and governance on Stacks.",
    isVerified: true,
  },
  {
    id: "6",
    rank: 6,
    name: "monadut",
    handle: "roman2dr4",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=roman2dr4",
    monthlyReward: 750,
    allTimeReward: 2700,
    contractsDeployed: 14,
    githubContributions: 42,
    walletAddress: "SP1QKFTEXKNGVBN6NBBQN6QBMJXHP3SXH16RMD3G",
    githubProfile: "https://github.com/roman2dr4",
    ecosystem: ["Infrastructure"],
    joinedDate: "2023-09-01",
    bio: "Node infrastructure and tooling for Stacks validators.",
    isVerified: false,
  },
  {
    id: "7",
    rank: 7,
    name: "dokapudge",
    handle: "drtpudge",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=drtpudge",
    monthlyReward: 750,
    allTimeReward: 2500,
    contractsDeployed: 6,
    githubContributions: 38,
    walletAddress: "SP3D03SHPKR0C9N89WFB3KGEQMJFQNCC4PT18ZGH",
    githubProfile: "https://github.com/drtpudge",
    ecosystem: ["NFT"],
    joinedDate: "2023-10-17",
    bio: "NFT marketplace contracts and royalty standards.",
    isVerified: true,
  },
  {
    id: "8",
    rank: 8,
    name: "Sukanto",
    handle: "sukanto01899",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=sukanto01899",
    monthlyReward: 750,
    allTimeReward: 2300,
    contractsDeployed: 4,
    githubContributions: 35,
    walletAddress: "SP1WN90HKT0E1FWCJT9JFPMC8YP7XGBGFNZGHRVJX",
    githubProfile: "https://github.com/sukanto01899",
    ecosystem: ["DeFi", "Social"],
    joinedDate: "2023-11-05",
    bio: "Social finance protocols on Stacks.",
    isVerified: false,
  },
  {
    id: "9",
    rank: 9,
    name: "madzvery",
    handle: "madzvery",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=madzvery",
    monthlyReward: 750,
    allTimeReward: 2100,
    contractsDeployed: 8,
    githubContributions: 31,
    walletAddress: "SP2QEZ06AGJ3RKJPBV14SY1V5BBFNAW33D96YPGZF",
    githubProfile: "https://github.com/madzvery",
    ecosystem: ["Gaming"],
    joinedDate: "2023-12-20",
    bio: "On-chain gaming assets and smart contract game logic.",
    isVerified: true,
  },
  {
    id: "10",
    rank: 10,
    name: "dangi",
    handle: "tanyarev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=tanyarev",
    monthlyReward: 750,
    allTimeReward: 1900,
    contractsDeployed: 3,
    githubContributions: 28,
    walletAddress: "SP3PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
    githubProfile: "https://github.com/tanyarev",
    ecosystem: ["DAO"],
    joinedDate: "2024-01-10",
    bio: "DAO governance and multi-sig tooling.",
    isVerified: false,
  },
  {
    id: "11",
    rank: 11,
    name: "stacksdev",
    handle: "stacksdev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stacksdev",
    monthlyReward: 420,
    allTimeReward: 1800,
    contractsDeployed: 11,
    githubContributions: 26,
    walletAddress: "SP1A2B3C4D5E6F7G8H9I0J1K2L3M4N5O6P7Q8R9S0",
    githubProfile: "https://github.com/stacksdev",
    ecosystem: ["Infrastructure", "DeFi"],
    joinedDate: "2024-01-25",
    bio: "Building core infrastructure for the Stacks ecosystem.",
    isVerified: true,
  },
  {
    id: "12",
    rank: 12,
    name: "bitcoinlayer",
    handle: "btclayer2",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=btclayer2",
    monthlyReward: 390,
    allTimeReward: 1650,
    contractsDeployed: 9,
    githubContributions: 22,
    walletAddress: "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS",
    githubProfile: "https://github.com/btclayer2",
    ecosystem: ["DeFi"],
    joinedDate: "2024-02-08",
    bio: "L2 bridge contracts and BTC-pegged token standards.",
    isVerified: false,
  },
  {
    id: "13",
    rank: 13,
    name: "clarity_dev",
    handle: "claritydev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=claritydev",
    monthlyReward: 360,
    allTimeReward: 1500,
    contractsDeployed: 16,
    githubContributions: 19,
    walletAddress: "SP3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5YC7D3C5",
    githubProfile: "https://github.com/claritydev",
    ecosystem: ["Infrastructure"],
    joinedDate: "2024-02-20",
    bio: "Clarity language tooling, linting, and IDE plugins.",
    isVerified: true,
  },
  {
    id: "14",
    rank: 14,
    name: "debielily",
    handle: "debielily",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=debielily",
    monthlyReward: 250,
    allTimeReward: 1200,
    contractsDeployed: 5,
    githubContributions: 8,
    walletAddress: "SP1DEBIELILY00000000000000000000000000000",
    githubProfile: "https://github.com/debielily",
    ecosystem: ["NFT", "Social"],
    joinedDate: "2024-03-01",
    bio: "Creator-focused tools and NFT social integrations.",
    isVerified: true,
  },
  {
    id: "15",
    rank: 15,
    name: "hirodev",
    handle: "hirobuilder",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=hirobuilder",
    monthlyReward: 330,
    allTimeReward: 1400,
    contractsDeployed: 7,
    githubContributions: 17,
    walletAddress: "SP4HIRO0000000000000000000000000000000000",
    githubProfile: "https://github.com/hirobuilder",
    ecosystem: ["Infrastructure"],
    joinedDate: "2024-03-10",
    bio: "Hiro platform integrations and developer tooling.",
    isVerified: false,
  },
  {
    id: "16",
    rank: 16,
    name: "nftsmith",
    handle: "nftsmith",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=nftsmith",
    monthlyReward: 310,
    allTimeReward: 1350,
    contractsDeployed: 13,
    githubContributions: 15,
    walletAddress: "SP5NFTSMITH000000000000000000000000000000",
    githubProfile: "https://github.com/nftsmith",
    ecosystem: ["NFT"],
    joinedDate: "2024-03-18",
    bio: "Minting, royalties, and fractionalization on Stacks.",
    isVerified: true,
  },
  {
    id: "17",
    rank: 17,
    name: "defiking",
    handle: "defiking",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=defiking",
    monthlyReward: 290,
    allTimeReward: 1280,
    contractsDeployed: 6,
    githubContributions: 14,
    walletAddress: "SP6DEFIKING00000000000000000000000000000",
    githubProfile: "https://github.com/defiking",
    ecosystem: ["DeFi"],
    joinedDate: "2024-04-02",
    bio: "AMM and yield farming protocols on Bitcoin L2.",
    isVerified: false,
  },
  {
    id: "18",
    rank: 18,
    name: "stacksguru",
    handle: "stacksguru",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stacksguru",
    monthlyReward: 275,
    allTimeReward: 1200,
    contractsDeployed: 4,
    githubContributions: 12,
    walletAddress: "SP7STACKSGURU0000000000000000000000000000",
    githubProfile: "https://github.com/stacksguru",
    ecosystem: ["DAO", "Infrastructure"],
    joinedDate: "2024-04-15",
    bio: "Governance frameworks and voting contracts.",
    isVerified: true,
  },
  {
    id: "19",
    rank: 19,
    name: "btcmaxi",
    handle: "btcmaxi_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=btcmaxi_dev",
    monthlyReward: 260,
    allTimeReward: 1150,
    contractsDeployed: 3,
    githubContributions: 11,
    walletAddress: "SP8BTCMAXI000000000000000000000000000000",
    githubProfile: "https://github.com/btcmaxi_dev",
    ecosystem: ["DeFi"],
    joinedDate: "2024-05-01",
    bio: "Bitcoin-native DeFi, no wrapped tokens needed.",
    isVerified: false,
  },
  {
    id: "20",
    rank: 20,
    name: "claritywiz",
    handle: "claritywiz",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=claritywiz",
    monthlyReward: 245,
    allTimeReward: 1100,
    contractsDeployed: 10,
    githubContributions: 9,
    walletAddress: "SP9CLARITYWIZ000000000000000000000000000",
    githubProfile: "https://github.com/claritywiz",
    ecosystem: ["Infrastructure"],
    joinedDate: "2024-05-14",
    bio: "Auditing and formal verification of Clarity contracts.",
    isVerified: true,
  },
  {
    id: "21",
    rank: 21,
    name: "sBTC_dev",
    handle: "sbtc_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=sbtc_dev",
    monthlyReward: 230,
    allTimeReward: 1050,
    contractsDeployed: 8,
    githubContributions: 8,
    walletAddress: "SP10SBTCDEV0000000000000000000000000000",
    githubProfile: "https://github.com/sbtc_dev",
    ecosystem: ["DeFi", "Infrastructure"],
    joinedDate: "2024-05-28",
    bio: "sBTC peg-in/out protocols and threshold signatures.",
    isVerified: true,
  },
  {
    id: "22",
    rank: 22,
    name: "gamestacks",
    handle: "gamestacks",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=gamestacks",
    monthlyReward: 215,
    allTimeReward: 980,
    contractsDeployed: 5,
    githubContributions: 7,
    walletAddress: "SP11GAMESTACKS000000000000000000000000000",
    githubProfile: "https://github.com/gamestacks",
    ecosystem: ["Gaming"],
    joinedDate: "2024-06-05",
    bio: "On-chain RPG mechanics and randomness contracts.",
    isVerified: false,
  },
  {
    id: "23",
    rank: 23,
    name: "daobuilder",
    handle: "daobuilder",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=daobuilder",
    monthlyReward: 200,
    allTimeReward: 920,
    contractsDeployed: 6,
    githubContributions: 6,
    walletAddress: "SP12DAOBUILDER00000000000000000000000000",
    githubProfile: "https://github.com/daobuilder",
    ecosystem: ["DAO"],
    joinedDate: "2024-06-19",
    bio: "Multi-sig wallets and treasury management DAOs.",
    isVerified: true,
  },
  {
    id: "24",
    rank: 24,
    name: "socialfi",
    handle: "socialfi_stx",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=socialfi_stx",
    monthlyReward: 185,
    allTimeReward: 860,
    contractsDeployed: 4,
    githubContributions: 5,
    walletAddress: "SP13SOCIALFI000000000000000000000000000",
    githubProfile: "https://github.com/socialfi_stx",
    ecosystem: ["Social"],
    joinedDate: "2024-07-03",
    bio: "Social tokens and creator economy on Stacks.",
    isVerified: false,
  },
  {
    id: "25",
    rank: 25,
    name: "ordinals_dev",
    handle: "ordinals_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ordinals_dev",
    monthlyReward: 175,
    allTimeReward: 800,
    contractsDeployed: 3,
    githubContributions: 4,
    walletAddress: "SP14ORDINALSDEV000000000000000000000000",
    githubProfile: "https://github.com/ordinals_dev",
    ecosystem: ["NFT"],
    joinedDate: "2024-07-17",
    bio: "Ordinals and inscriptions tooling on Bitcoin.",
    isVerified: true,
  },
  {
    id: "26",
    rank: 26,
    name: "stackpool",
    handle: "stackpool",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stackpool",
    monthlyReward: 165,
    allTimeReward: 750,
    contractsDeployed: 7,
    githubContributions: 3,
    walletAddress: "SP15STACKPOOL000000000000000000000000000",
    githubProfile: "https://github.com/stackpool",
    ecosystem: ["DeFi"],
    joinedDate: "2024-07-30",
    bio: "Stacking pool contracts and reward distribution.",
    isVerified: false,
  },
  {
    id: "27",
    rank: 27,
    name: "velar_dev",
    handle: "velar_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=velar_dev",
    monthlyReward: 155,
    allTimeReward: 700,
    contractsDeployed: 5,
    githubContributions: 3,
    walletAddress: "SP16VELARDEV0000000000000000000000000000",
    githubProfile: "https://github.com/velar_dev",
    ecosystem: ["DeFi"],
    joinedDate: "2024-08-10",
    bio: "DEX and perpetuals on Stacks.",
    isVerified: true,
  },
  {
    id: "28",
    rank: 28,
    name: "alexlab",
    handle: "alexlab_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alexlab_dev",
    monthlyReward: 145,
    allTimeReward: 650,
    contractsDeployed: 9,
    githubContributions: 2,
    walletAddress: "SP17ALEXLABDEV00000000000000000000000000",
    githubProfile: "https://github.com/alexlab_dev",
    ecosystem: ["DeFi"],
    joinedDate: "2024-08-22",
    bio: "ALEX protocol integrations and liquidity incentives.",
    isVerified: false,
  },
  {
    id: "29",
    rank: 29,
    name: "btcname",
    handle: "btcname_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=btcname_dev",
    monthlyReward: 135,
    allTimeReward: 600,
    contractsDeployed: 4,
    githubContributions: 2,
    walletAddress: "SP18BTCNAMEDEV00000000000000000000000000",
    githubProfile: "https://github.com/btcname_dev",
    ecosystem: ["Infrastructure", "Social"],
    joinedDate: "2024-09-03",
    bio: "BNS names and identity on Stacks.",
    isVerified: true,
  },
  {
    id: "30",
    rank: 30,
    name: "clarity_audit",
    handle: "clarity_audit",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=clarity_audit",
    monthlyReward: 125,
    allTimeReward: 560,
    contractsDeployed: 2,
    githubContributions: 1,
    walletAddress: "SP19CLARITYAUDIT000000000000000000000000",
    githubProfile: "https://github.com/clarity_audit",
    ecosystem: ["Infrastructure"],
    joinedDate: "2024-09-15",
    bio: "Security audits and bug bounty for Clarity contracts.",
    isVerified: false,
  },
  {
    id: "31",
    rank: 31,
    name: "stxpay",
    handle: "stxpay",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxpay",
    monthlyReward: 120,
    allTimeReward: 540,
    contractsDeployed: 6,
    githubContributions: 5,
    walletAddress: "SP20STXPAY0000000000000000000000000000",
    githubProfile: "https://github.com/stxpay",
    ecosystem: ["DeFi", "Social"],
    joinedDate: "2024-09-28",
    bio: "Payment channels and micro-transactions on Stacks.",
    isVerified: true,
  },
  {
    id: "32",
    rank: 32,
    name: "nftdrop",
    handle: "nftdrop_stx",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=nftdrop_stx",
    monthlyReward: 115,
    allTimeReward: 510,
    contractsDeployed: 8,
    githubContributions: 4,
    walletAddress: "SP21NFTDROPSTX00000000000000000000000000",
    githubProfile: "https://github.com/nftdrop_stx",
    ecosystem: ["NFT"],
    joinedDate: "2024-10-05",
    bio: "NFT launchpad and fair drop mechanisms.",
    isVerified: false,
  },
  {
    id: "33",
    rank: 33,
    name: "governance_xyz",
    handle: "governance_xyz",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=governance_xyz",
    monthlyReward: 110,
    allTimeReward: 490,
    contractsDeployed: 3,
    githubContributions: 6,
    walletAddress: "SP22GOVERNANCEXYZ0000000000000000000000",
    githubProfile: "https://github.com/governance_xyz",
    ecosystem: ["DAO"],
    joinedDate: "2024-10-18",
    bio: "On-chain proposals and snapshot voting on Stacks.",
    isVerified: true,
  },
  {
    id: "34",
    rank: 34,
    name: "btcstaker",
    handle: "btcstaker",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=btcstaker",
    monthlyReward: 105,
    allTimeReward: 470,
    contractsDeployed: 4,
    githubContributions: 3,
    walletAddress: "SP23BTCSTAKER00000000000000000000000000",
    githubProfile: "https://github.com/btcstaker",
    ecosystem: ["DeFi"],
    joinedDate: "2024-10-30",
    bio: "Native stacking and BTC yield generation.",
    isVerified: false,
  },
  {
    id: "35",
    rank: 35,
    name: "openbuilder",
    handle: "openbuilder",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=openbuilder",
    monthlyReward: 100,
    allTimeReward: 450,
    contractsDeployed: 5,
    githubContributions: 8,
    walletAddress: "SP24OPENBUILDER0000000000000000000000000",
    githubProfile: "https://github.com/openbuilder",
    ecosystem: ["Infrastructure"],
    joinedDate: "2024-11-08",
    bio: "Open-source tooling for Stacks developers.",
    isVerified: true,
  },
  {
    id: "36",
    rank: 36,
    name: "metaverse_stx",
    handle: "metaverse_stx",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=metaverse_stx",
    monthlyReward: 95,
    allTimeReward: 430,
    contractsDeployed: 2,
    githubContributions: 2,
    walletAddress: "SP25METAVERSESTX0000000000000000000000",
    githubProfile: "https://github.com/metaverse_stx",
    ecosystem: ["Gaming", "NFT"],
    joinedDate: "2024-11-20",
    bio: "Metaverse land registry on Bitcoin L2.",
    isVerified: false,
  },
  {
    id: "37",
    rank: 37,
    name: "bridge_dev",
    handle: "bridge_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=bridge_dev",
    monthlyReward: 90,
    allTimeReward: 410,
    contractsDeployed: 3,
    githubContributions: 5,
    walletAddress: "SP26BRIDGEDEV00000000000000000000000000",
    githubProfile: "https://github.com/bridge_dev",
    ecosystem: ["Infrastructure", "DeFi"],
    joinedDate: "2024-12-02",
    bio: "Cross-chain bridge contracts for Stacks.",
    isVerified: true,
  },
  {
    id: "38",
    rank: 38,
    name: "stxtoken",
    handle: "stxtoken",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxtoken",
    monthlyReward: 85,
    allTimeReward: 390,
    contractsDeployed: 6,
    githubContributions: 3,
    walletAddress: "SP27STXTOKEN000000000000000000000000000",
    githubProfile: "https://github.com/stxtoken",
    ecosystem: ["DeFi"],
    joinedDate: "2024-12-14",
    bio: "SIP-010 fungible token factory and airdrop tooling.",
    isVerified: false,
  },
  {
    id: "39",
    rank: 39,
    name: "clarity_labs",
    handle: "clarity_labs",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=clarity_labs",
    monthlyReward: 80,
    allTimeReward: 370,
    contractsDeployed: 4,
    githubContributions: 7,
    walletAddress: "SP28CLARITYLABS0000000000000000000000",
    githubProfile: "https://github.com/clarity_labs",
    ecosystem: ["Infrastructure"],
    joinedDate: "2024-12-27",
    bio: "Research and development for Clarity smart contracts.",
    isVerified: true,
  },
  {
    id: "40",
    rank: 40,
    name: "stackscan",
    handle: "stackscan",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stackscan",
    monthlyReward: 75,
    allTimeReward: 350,
    contractsDeployed: 1,
    githubContributions: 9,
    walletAddress: "SP29STACKSCAN0000000000000000000000000",
    githubProfile: "https://github.com/stackscan",
    ecosystem: ["Infrastructure"],
    joinedDate: "2025-01-05",
    bio: "Block explorer and analytics for the Stacks network.",
    isVerified: false,
  },
  {
    id: "41",
    rank: 41,
    name: "zerostx",
    handle: "zerostx",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=zerostx",
    monthlyReward: 70,
    allTimeReward: 330,
    contractsDeployed: 3,
    githubContributions: 4,
    walletAddress: "SP30ZEROSTX000000000000000000000000000",
    githubProfile: "https://github.com/zerostx",
    ecosystem: ["DeFi"],
    joinedDate: "2025-01-18",
    bio: "Zero-knowledge proofs on Stacks.",
    isVerified: true,
  },
  {
    id: "42",
    rank: 42,
    name: "pixelnft",
    handle: "pixelnft",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=pixelnft",
    monthlyReward: 65,
    allTimeReward: 310,
    contractsDeployed: 7,
    githubContributions: 2,
    walletAddress: "SP31PIXELNFT0000000000000000000000000",
    githubProfile: "https://github.com/pixelnft",
    ecosystem: ["NFT"],
    joinedDate: "2025-01-30",
    bio: "Pixel art NFTs with on-chain trait generation.",
    isVerified: false,
  },
  {
    id: "43",
    rank: 43,
    name: "stxlend",
    handle: "stxlend",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxlend",
    monthlyReward: 60,
    allTimeReward: 290,
    contractsDeployed: 5,
    githubContributions: 3,
    walletAddress: "SP32STXLEND000000000000000000000000000",
    githubProfile: "https://github.com/stxlend",
    ecosystem: ["DeFi"],
    joinedDate: "2025-02-08",
    bio: "Lending and borrowing protocols on Bitcoin L2.",
    isVerified: true,
  },
  {
    id: "44",
    rank: 44,
    name: "multisig_dev",
    handle: "multisig_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=multisig_dev",
    monthlyReward: 55,
    allTimeReward: 270,
    contractsDeployed: 2,
    githubContributions: 5,
    walletAddress: "SP33MULTISIGDEV0000000000000000000000",
    githubProfile: "https://github.com/multisig_dev",
    ecosystem: ["DAO", "Infrastructure"],
    joinedDate: "2025-02-18",
    bio: "Safe-style multi-sig contracts for Stacks.",
    isVerified: false,
  },
  {
    id: "45",
    rank: 45,
    name: "stxgrant",
    handle: "stxgrant",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxgrant",
    monthlyReward: 50,
    allTimeReward: 250,
    contractsDeployed: 1,
    githubContributions: 10,
    walletAddress: "SP34STXGRANT0000000000000000000000000",
    githubProfile: "https://github.com/stxgrant",
    ecosystem: ["DAO"],
    joinedDate: "2025-03-01",
    bio: "Grant streaming and milestone-based funding on Stacks.",
    isVerified: true,
  },
  {
    id: "46",
    rank: 46,
    name: "inscriber",
    handle: "inscriber",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=inscriber",
    monthlyReward: 45,
    allTimeReward: 230,
    contractsDeployed: 3,
    githubContributions: 2,
    walletAddress: "SP35INSCRIBER000000000000000000000000",
    githubProfile: "https://github.com/inscriber",
    ecosystem: ["NFT"],
    joinedDate: "2025-03-12",
    bio: "Bitcoin inscription tools and marketplaces.",
    isVerified: false,
  },
  {
    id: "47",
    rank: 47,
    name: "stxwatch",
    handle: "stxwatch",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxwatch",
    monthlyReward: 40,
    allTimeReward: 210,
    contractsDeployed: 0,
    githubContributions: 11,
    walletAddress: "SP36STXWATCH0000000000000000000000000",
    githubProfile: "https://github.com/stxwatch",
    ecosystem: ["Infrastructure"],
    joinedDate: "2025-03-20",
    bio: "Real-time monitoring and alerting for Stacks contracts.",
    isVerified: true,
  },
  {
    id: "48",
    rank: 48,
    name: "stxpunk",
    handle: "stxpunk",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxpunk",
    monthlyReward: 35,
    allTimeReward: 190,
    contractsDeployed: 4,
    githubContributions: 1,
    walletAddress: "SP37STXPUNK000000000000000000000000000",
    githubProfile: "https://github.com/stxpunk",
    ecosystem: ["NFT"],
    joinedDate: "2025-04-02",
    bio: "CryptoPunks-style generative NFT collection on Stacks.",
    isVerified: false,
  },
  {
    id: "49",
    rank: 49,
    name: "yield_dev",
    handle: "yield_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=yield_dev",
    monthlyReward: 30,
    allTimeReward: 170,
    contractsDeployed: 2,
    githubContributions: 3,
    walletAddress: "SP38YIELDDEV000000000000000000000000000",
    githubProfile: "https://github.com/yield_dev",
    ecosystem: ["DeFi"],
    joinedDate: "2025-04-14",
    bio: "Yield aggregators and auto-compounders on Stacks.",
    isVerified: true,
  },
  {
    id: "50",
    rank: 50,
    name: "stackshero",
    handle: "stackshero",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stackshero",
    monthlyReward: 25,
    allTimeReward: 150,
    contractsDeployed: 1,
    githubContributions: 2,
    walletAddress: "SP39STACKSHERO000000000000000000000000",
    githubProfile: "https://github.com/stackshero",
    ecosystem: ["Social"],
    joinedDate: "2025-04-25",
    bio: "Community hero — contributions, tutorials, and docs.",
    isVerified: false,
  },
  {
    id: "51",
    rank: 51,
    name: "stackslabs",
    handle: "stackslabs",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stackslabs51",
    monthlyReward: 22,
    allTimeReward: 140,
    contractsDeployed: 2,
    githubContributions: 4,
    walletAddress: "SP40STACKSLABS000000000000000000000000",
    githubProfile: "https://github.com/stackslabs",
    ecosystem: ["Infrastructure"],
    joinedDate: "2025-05-01",
    bio: "Research arm pushing Stacks protocol improvements.",
    isVerified: true,
  },
  {
    id: "52",
    rank: 52,
    name: "btcfi",
    handle: "btcfi_dev",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=btcfi_dev",
    monthlyReward: 20,
    allTimeReward: 130,
    contractsDeployed: 3,
    githubContributions: 2,
    walletAddress: "SP41BTCFIDEV0000000000000000000000000",
    githubProfile: "https://github.com/btcfi_dev",
    ecosystem: ["DeFi"],
    joinedDate: "2025-05-09",
    bio: "BTC-native finance without intermediaries.",
    isVerified: false,
  },
  {
    id: "53",
    rank: 53,
    name: "stxdao",
    handle: "stxdao",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxdao53",
    monthlyReward: 18,
    allTimeReward: 120,
    contractsDeployed: 1,
    githubContributions: 5,
    walletAddress: "SP42STXDAO000000000000000000000000000",
    githubProfile: "https://github.com/stxdao",
    ecosystem: ["DAO"],
    joinedDate: "2025-05-18",
    bio: "Community governance for public Stacks infrastructure.",
    isVerified: true,
  },
  {
    id: "54",
    rank: 54,
    name: "stxgame",
    handle: "stxgame",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxgame54",
    monthlyReward: 16,
    allTimeReward: 110,
    contractsDeployed: 2,
    githubContributions: 3,
    walletAddress: "SP43STXGAME0000000000000000000000000",
    githubProfile: "https://github.com/stxgame",
    ecosystem: ["Gaming"],
    joinedDate: "2025-05-27",
    bio: "Blockchain-verified game item ownership.",
    isVerified: false,
  },
  {
    id: "55",
    rank: 55,
    name: "stxsocial",
    handle: "stxsocial",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxsocial55",
    monthlyReward: 14,
    allTimeReward: 100,
    contractsDeployed: 1,
    githubContributions: 4,
    walletAddress: "SP44STXSOCIAL000000000000000000000000",
    githubProfile: "https://github.com/stxsocial",
    ecosystem: ["Social"],
    joinedDate: "2025-06-04",
    bio: "Decentralised social graph on Bitcoin.",
    isVerified: true,
  },
  {
    id: "56",
    rank: 56,
    name: "stxbridge",
    handle: "stxbridge",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxbridge56",
    monthlyReward: 12,
    allTimeReward: 90,
    contractsDeployed: 3,
    githubContributions: 2,
    walletAddress: "SP45STXBRIDGE00000000000000000000000",
    githubProfile: "https://github.com/stxbridge",
    ecosystem: ["Infrastructure"],
    joinedDate: "2025-06-13",
    bio: "Trustless bridge between Stacks and EVM chains.",
    isVerified: false,
  },
  {
    id: "57",
    rank: 57,
    name: "stxmarket",
    handle: "stxmarket",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxmarket57",
    monthlyReward: 10,
    allTimeReward: 80,
    contractsDeployed: 4,
    githubContributions: 1,
    walletAddress: "SP46STXMARKET000000000000000000000000",
    githubProfile: "https://github.com/stxmarket",
    ecosystem: ["NFT", "DeFi"],
    joinedDate: "2025-06-22",
    bio: "NFT marketplace with DeFi liquidity integration.",
    isVerified: true,
  },
  {
    id: "58",
    rank: 58,
    name: "stxlens",
    handle: "stxlens",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxlens58",
    monthlyReward: 8,
    allTimeReward: 70,
    contractsDeployed: 1,
    githubContributions: 3,
    walletAddress: "SP47STXLENS0000000000000000000000000",
    githubProfile: "https://github.com/stxlens",
    ecosystem: ["Social"],
    joinedDate: "2025-07-01",
    bio: "Lens-style social protocol on Bitcoin L2.",
    isVerified: false,
  },
  {
    id: "59",
    rank: 59,
    name: "stxoracle",
    handle: "stxoracle",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxoracle59",
    monthlyReward: 6,
    allTimeReward: 60,
    contractsDeployed: 2,
    githubContributions: 2,
    walletAddress: "SP48STXORACLE000000000000000000000000",
    githubProfile: "https://github.com/stxoracle",
    ecosystem: ["Infrastructure", "DeFi"],
    joinedDate: "2025-07-10",
    bio: "On-chain price oracles for Stacks DeFi.",
    isVerified: true,
  },
  {
    id: "60",
    rank: 60,
    name: "stxnewbie",
    handle: "stxnewbie",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=stxnewbie60",
    monthlyReward: 4,
    allTimeReward: 50,
    contractsDeployed: 0,
    githubContributions: 1,
    walletAddress: "SP49STXNEWBIE000000000000000000000000",
    githubProfile: "https://github.com/stxnewbie",
    ecosystem: ["Social"],
    joinedDate: "2025-07-20",
    bio: "Just getting started on the Stacks journey.",
    isVerified: false,
  },
];

export const CURRENT_REWARD_PROGRAM: RewardProgram = {
  id: "feb-2025",
  name: "Stacks Builder Rewards: February",
  totalPrize: 15000,
  currency: "STX",
  winnerCount: 50,
  startDate: "2025-02-01",
  endDate: "2025-02-28",
  ecosystem: "Stacks",
};

export const TOTAL_BUILDERS = 549;

// ─── Mock current user activity ───────────────────────────────────────────────

import type { UserActivity, FAQItem } from "@/types";

export const MOCK_USER_ACTIVITY: UserActivity = {
  wallet: {
    status: "connected",
    address: "SP1DEBIELILY00000000000000000000000000000",
    count: 3,
  },
  github: {
    status: "connected",
    handle: "debielily",
    contributions: 8,
  },
  contractsDeployed: 5,
  estimatedReward: 250,
  rank: 14,
  rewardCompleted: true,
};

// ─── FAQ items ────────────────────────────────────────────────────────────────

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: "quick-start",
    question: "Quick Start Guide",
    answer:
      "Connect your Stacks wallet and GitHub profile from the Rewards page. Once both are linked, your onchain activity and GitHub contributions will be tracked automatically. The leaderboard updates daily.",
  },
  {
    id: "eligibility",
    question: "How can I become eligible?",
    answer:
      "To be eligible, you must connect at least one Stacks (Bitcoin L2) wallet and one GitHub account. Activity is tracked from the first day of each monthly program. Deploying verified smart contracts and contributing to public Stacks repositories increases your score.",
  },
  {
    id: "schedule",
    question: "What's the program schedule?",
    answer:
      "Each reward program runs for one calendar month (e.g., Feb 1–28). A new program starts on the 1st of every month. Rewards from the previous program are distributed within 7 days of the program closing.",
  },
  {
    id: "calculation",
    question: "How are rewards calculated?",
    answer:
      "Rewards are calculated based on two weighted categories: (1) Onchain activity — users and fees generated by your deployed smart contracts on Stacks, and (2) GitHub contributions — commits, pull requests, and issues on public Stacks-related repositories. Builders are ranked by combined score and the top 50 share the prize pool.",
  },
  {
    id: "tokens",
    question: "How many tokens are distributed?",
    answer:
      "Each monthly program distributes 15,000 $STX across 50 winners. The top 3 builders each receive 750 $STX. Rewards decrease progressively down the leaderboard. All reward amounts are estimates until the program closes.",
  },
  {
    id: "distribution",
    question: "How are rewards distributed?",
    answer:
      "Rewards are sent directly to your connected Stacks wallet within 7 days of program close. No claim is required — distributions are automated via smart contract.",
  },
  {
    id: "receive",
    question: "How do I receive rewards?",
    answer:
      "Rewards are sent automatically to the primary Stacks wallet address you connected to Buildr. Make sure your wallet is still connected and the address is valid at the end of the program period.",
  },
  {
    id: "history",
    question: "Where can I check my reward transaction history?",
    answer:
      "Your reward transaction history is visible on any Stacks block explorer (e.g., explorer.hiro.so) by searching your wallet address. Buildr will also show a summary in your profile activity section.",
  },
  {
    id: "leaderboard-update",
    question: "How often does the leaderboard update?",
    answer:
      "The leaderboard updates once every 24 hours. Changes from onchain transactions and GitHub contributions made today will appear on tomorrow's leaderboard.",
  },
  {
    id: "appear",
    question: "I met the eligibility requirements. When will I appear on the leaderboard?",
    answer:
      "After connecting your wallet and GitHub, it can take up to 24 hours for your profile to appear on the leaderboard as we index your activity. If you still don't appear after 48 hours, contact support.",
  },
  {
    id: "flagged",
    question: "My activity is flagged as unusual. Why did this happen and what should I do?",
    answer:
      "Buildr monitors for wash trading, bot-generated GitHub activity, and self-referral loops. If your activity is flagged, you'll receive a notification. You can appeal by submitting a support request with evidence of legitimate activity.",
  },
  {
    id: "stuck",
    question: "My GitHub/Onchain/other category progress is stuck. Is my data being tracked correctly?",
    answer:
      "Data indexing can take up to 24 hours. If your progress hasn't updated after 48 hours, try disconnecting and reconnecting your wallet or GitHub. If the issue persists, submit a support request.",
  },
  {
    id: "support",
    question: "My question is not covered here. Where can I get support?",
    answer:
      "Join the Stacks Discord (#buildr-support channel) or open a GitHub issue on the Buildr repository. The team typically responds within 24 hours on weekdays.",
  },
  {
    id: "terms",
    question: "Is there a Terms & Conditions page?",
    answer:
      "Yes. You can review the full Terms & Conditions from the footer of any Buildr page. By connecting your wallet and participating in reward programs, you agree to the Buildr Terms of Service.",
  },
];
